"""Pydantic schemas for the stream-society simulator."""

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class Persona(BaseModel):
    """Viewer persona definition."""

    persona_id: str
    name: str
    age: int
    occupation: str
    interests: List[str]
    persona_group: str
    communication_style: str
    base_activity_level: float = Field(ge=0.0, le=1.0)
    language: str = "ja"


class ViewerState(BaseModel):
    """Dynamic state of a viewer during a simulation run."""

    viewer_id: str
    persona_id: str
    persona_group: str
    interest_by_topic: Dict[str, float] = Field(default_factory=dict)
    affinity_to_streamer: float = Field(default=0.5, ge=0.0, le=1.0)
    activity_level: float = Field(default=0.5, ge=0.0, le=1.0)
    emotion_state: str = "neutral"
    participation_style: str = "lurker"


class CommentCandidate(BaseModel):
    """A comment generated by a viewer agent."""

    comment_id: str
    viewer_id: str
    persona_id: str
    persona_group: str
    text: str
    timestamp_turn: int
    topic: str
    sentiment: float = Field(ge=-1.0, le=1.0)
    question_flag: bool = False
    toxicity_score: float = Field(default=0.0, ge=0.0, le=1.0)
    novelty_score: float = Field(default=0.5, ge=0.0, le=1.0)


class StreamerResponse(BaseModel):
    """A response generated by the streamer agent."""

    response_id: str
    selected_comment_id: str
    selected_viewer_id: str
    response_text: str
    policy_used: str
    timestamp_turn: int
    metadata: Dict = Field(default_factory=dict)


class TurnLog(BaseModel):
    """Log of a single simulation turn."""

    turn_id: int
    timestamp_turn: int
    comment_candidates: List[CommentCandidate] = Field(default_factory=list)
    selected_comment: Optional[CommentCandidate] = None
    streamer_response: Optional[StreamerResponse] = None
    active_viewers: int = 0
    metrics: Dict = Field(default_factory=dict)


class RunConfig(BaseModel):
    """Configuration for a simulation run."""

    run_id: str
    experiment_name: str
    seed: int = 42
    num_viewers: int = 10
    num_turns: int = 20
    policy: str = "random"
    streamer_config: Dict = Field(default_factory=dict)
    description: str = ""


class RunSummary(BaseModel):
    """Summary metrics for a completed simulation run."""

    run_id: str
    experiment_name: str
    policy: str
    num_turns: int
    num_viewers: int
    total_comments: int
    engagement_proxy: float
    unique_participant_rate: float
    topic_diversity: float
    safety_rate: float
    sentiment_shift: float
